flags: {}
packages:
- .
extra-deps:
- digestive-functors-0.8.4.0
- digestive-functors-heist-0.8.8.1
- digestive-functors-snap-0.7.0.1
- heist-1.1.0.1
- map-syntax-0.3
- pwstore-fast-2.4.4
- snap-1.1.1.0
- snap-extras-0.12.2.1
- xmlhtml-0.2.5.2
resolver: lts-12.21
